### ISSUE TITLE
exports is not defined 问题记录

### ISSUE THREAD

**Issue by xiaoxiaojx** [xiaoxiaojx/blog#27]
![image](https://user-images.githubusercontent.com/23253540/150164484-1b868d2b-a9fa-45f2-882f-bd77d1942701.png)

## 问题定位
报错信息如下
```bash
Uncaught ReferenceError: exports is not defined
    at Module.<anonymous> (browser.js:13:1)
    at Module../node_modules/.pnpm/abort-controller@3.0.0/node_modules/abort-controller/dist/abort-controller.js (abort-controller.ts:62:1)
    at __webpack_require__ (bootstrap:84:1)
    at Object.<anonymous> (polyfill.js:4:1)
    at Object../node_modules/.pnpm/abort-controller@3.0.0/node_modules/abort-controller/polyfill.js (polyfill.js:21:1)
    at __webpack_require__ (bootstrap:84:1)
```
首先查看 node_modules 中 abort-controller 包的代码, 找到报错的地方, 为下图中红色下划线标出的有 exports 变量这一行的代码
```js
// abort-controller/dist/abort-controller.js
```
![image](https://user-images.githubusercontent.com/23253540/150134616-4bf6f483-682a-4b9e-a0d1-f8e7c00db8e6.png)
仔细查看发现代码并无明显语法错误

正常来说 webpack 打包过后会把该模块的代码放在一个闭包函数中去运行, 通过函数参数中传入 module, exports 等变量, 运行完成后 module, exports 的值即为该模块的导出来的值, 和 Node.js 编译运行一个 js 文件模块的原理是类似的, 如下所示👇
![0b044a8c6c1554aa6447b7331906cb8534dea5df](https://user-images.githubusercontent.com/23253540/150135046-22452239-cf28-45f5-9034-af94620f12bd.png)

但是这里报错的地方的闭包函数却不长上面那样, 区别是该闭包函数传入的参数值是 __webpack_exports__ 而非 exports ?!
![9d2daf8013a79151faa421b2eb55405962fb10b9](https://user-images.githubusercontent.com/23253540/150136078-f1aff4df-086d-48b4-aace-4bba88072e62.png)
所以代码在浏览器运行时该模块作用域内没有 exports, 就出现了本文开始的错误信息 exports is not defined ❌
```js
// abort-controller/dist/abort-controller.js

exports.AbortController = AbortController;
```
🤔 那么是什么条件决定了形参何时命名为 __webpack_exports__, 何时为 exports 了 ? 接着去探寻一下 webpack 这部分的代码

通过下面的代码我们发现 isHarmony 变量的值为 true 则会命名为 __webpack_exports__, isHarmony 为 true 的条件我们发现其实是当前有 import、export 等 ES-Module 语句时, 可想而知 CommonJs 则会命名为 exports
```
// webpack/lib/dependencies/HarmonyDetectionParserPlugin.js

module.exports = class HarmonyDetectionParserPlugin {
	apply(parser) {
		parser.hooks.program.tap("HarmonyDetectionParserPlugin", ast => {
			const isHarmony =
				isStrictHarmony ||
				ast.body.some(
					statement =>
						statement.type === "ImportDeclaration" ||
						statement.type === "ExportDefaultDeclaration" ||
						statement.type === "ExportNamedDeclaration" ||
						statement.type === "ExportAllDeclaration"
				);
			if (isHarmony) {
				// ...
				module.buildInfo.exportsArgument = "__webpack_exports__";

			}
		});
```
这也容易理解, 当发现该文件是 ES-Module 模块时, 没有必要传入 exports, 因为 CommonJs 导出模块变量时才会去 exports 上面去赋值导出变量, 所以 ES-Module 模块里面 exports 变量不是一个关键词, 用户可以像普通变量一样使用

🤯 不过我们回头看一下, 报错的 abort-controller 包在 node_modules 中的代码不就是 CommonJs 规范的吗, 按理函数的入参是 exports 才对

> 💡 这里要补充的知识是像 create-react-app、next、jest 等 Node 工具都默认不会让 babel 去处理 node_modules 中包的代码, 因为按规范, 每个包发布到 npm 中时都最好是 es5 等兼容性良好的代码, 而非 jsx, ts 等需要二次编译的代码

而报错的该包因为如下有 const 语句的 es6 代码 ⚠️   为了兼容低版本的浏览器, 我们的脚手架中开了一个口子去白名单开放编译 node_modules 中的不规范的包
```
// abort-controller/dist/abort-controller.js

class AbortController {
// ...
}
/**
 * Associated signals.
 */
const signals = new WeakMap();
```
既然经过了一次 babel-loader, 那么我们需要知道 abort-controller 代码经过 babel-loader 编译后交给 webpack 处理时的代码长什么样子

接着看看我们的 babel 配置的 preset 使用的是 babel-preset-react-app
```js
// webpack 的配置

{
      loader: require.resolve('babel-loader'),
      options: {
        babelrc: false,
        presets: [require.resolve('babel-preset-react-app')],
        plugins: [
          // ...
        ],
        cacheDirectory: !isProd
      }
```
深入 babel-preset-react-app 的代码, 发现其内置使用了 @babel/plugin-transform-runtime 插件
```
// babel-preset-react-app/create.js

module.exports = function(api, opts, env) {
      // Polyfills the runtime needed for async/await, generators, and friends
      // https://babeljs.io/docs/en/babel-plugin-transform-runtime
      [
        require('@babel/plugin-transform-runtime').default,
        {
          // ...
        },
};
```
transform-runtime 的作用是当检测到该文件代码中有 es6 等高语法的代码时, 会通过在文件顶部添加 import 等语句动态添加对应的 polyfill, 达到按需添加 polyfill 的作用

相比直接把如下的 _classCallCheck 等实现的代码直接插入到文件头部, 通过 import 一行代码动态添加能够有效避免每个文件中都有这些重复的 polyfill 代码, 所以使用 transform-runtime 也算一个常见的优化手段

![65c96974a8d723dff68bb033c70abb1c52df4ecb](https://user-images.githubusercontent.com/23253540/150140716-6ee33c90-fdf7-4e6c-8f2e-c04e8592a2a0.png)

😯 到这里我们知道了 abort-controller 这个包在 node_modules 中的代码虽然是 CommonJs, 但是通过 transform-runtime 给其添加的 import 语句, 使得 webpack 判断它为 ES-Module 模块了

接着我们只能探索 transform-runtime 是否能通过 require 来动态添加 polyfill 了, 这样 webpack 也不会误判了。

通过查看插入 import 语句实现的代码，此时我们是因为进入了下图 isModuleForBabel 为 true 的逻辑, 而 builder.import() 显然就是添加一个 import AST 的函数实现。如果能进入 else 的逻辑使用上 builder.require(); 逻辑不就解决了我们的问题 !

```js
// @babel/helper-module-imports/lib/import-injector.js
```
![image](https://user-images.githubusercontent.com/23253540/150141909-77321d19-0b21-46aa-a895-9b5a185bf0ff.png)

然而 transform-runtime 调用的 _helperModuleImports.addDefault 函数传的参数尽然是写死的  😓 不得不让我们怀疑是 transform-runtime 的一个 bug
```js
// @babel/plugin-transform-runtime/lib/index.js

this.addDefaultImport = (source, nameHint, blockHoist) => {
  const cacheKey = (0, _helperModuleImports.isModule)(file.path);
  const key = `${source}:${nameHint}:${cacheKey || ""}`;
  let cached = cache.get(key);

  if (cached) {
    cached = _core.types.cloneNode(cached);
  } else {
    cached = (0, _helperModuleImports.addDefault)(file.path, source, {
      importedInterop: "uncompiled",
      nameHint,
      blockHoist
    });
    cache.set(key, cached);
  }

  return cached;
};
},
```
## 问题解决
1. 尝试从源头 @babel/plugin-transform-runtime 解决
2. 对 abort-controller 这些不太规范的包使用单独的 babel 配置

**Comment by candisecandise** [comment]
为什么  abort-controller  打出来的包还会有 es6 的代码

**Comment by xiaoxiaojx** [comment]
> 为什么 abort-controller 打出来的包还会有 es6 的代码

没有 es6 的代码，import 是 @babel/plugin-transform-runtime 自动添加的

**Comment by thjttk** [comment]
各种模块化方案真是万恶之源啊
CJS,ESM,AMD,UMD,IIFE

**Comment by thjttk** [comment]
![image](https://user-images.githubusercontent.com/4099583/211757947-1239cd66-1b3b-4173-b108-20bf9ac390b6.png)
<img width="615" alt="image" src="https://user-images.githubusercontent.com/4099583/211758404-f6c06cec-24ad-47c5-8a47-6e874411ed81.png">

@babel/plguin-transform-runtime 是可以配置（新版根据package.json字段）插入的 helper 是 ESM 形式还是 CJS 形式。这个 case 如果走了 CJS 应该就没有问题了

**Comment by biorz** [comment]
666

**Comment by eczn** [comment]
刚遇到了，还挺复杂。。

**Comment by tommyZZM** [comment]
webpack 就是一坨一坨一坨，真恶心

**Comment by ParseDark** [comment]
Thank! It's works
